on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GOOGLE_PROJECT }}
          service_account_key: ${{ env.GOOGLE_CREDENTIALS }}
          export_default_credentials: true

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan -out=tfplan
        if: github.event_name == 'pull_request'

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve tfplan
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

      - name: Run Tests
        run: |
          chmod +x test.sh
          ./test.sh
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

      - name: Export Outputs
        run: |
          cd terraform
          echo "LB_URL=$(terraform output -raw load_balancer_url)" >> $GITHUB_ENV
          echo "FUNCTION_URL=$(terraform output -raw function_url)" >> $GITHUB_ENV
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
